import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CartSidebar from "./components/CartSidebar";
import { CartProvider } from "./components/CartProvider";
import Navbar from "./components/Navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon: "/favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <link rel="icon" href="/favicon.ico" sizes="any" />

      <body className={inter.className + " relative overflow-x-hidden"}>
        <CartProvider>
          <Navbar></Navbar>
          {children}
        </CartProvider>
        <div className=""></div>
      </body>
    </html>
  );
}
